/**
 * Shared method vocabulary for the source-policy and runtime-trace passes.
 * These sets describe the educational shim surface, not the complete
 * Playwright API.
 */
export const PLAYWRIGHT_ACTION_METHODS: ReadonlySet<string> = new Set([
  'click',
  'dblclick',
  'fill',
  'check',
  'uncheck',
  'selectOption',
  'focus',
  'blur',
  'clear',
  'dispatchEvent',
  'setInputFiles',
  'dragTo',
  'dragAndDrop',
  'press',
  'hover',
  'waitFor',
]);

export const PLAYWRIGHT_LOCATOR_RETURNING_METHODS: ReadonlySet<string> = new Set([
  'frameLocator',
  'locator',
  'getByRole',
  'getByText',
  'getByLabel',
  'getByPlaceholder',
  'getByAltText',
  'getByTitle',
  'getByTestId',
  'filter',
  'first',
  'last',
  'nth',
]);

export const PLAYWRIGHT_PAGE_METHODS: ReadonlySet<string> = new Set([
  'on',
  'route',
  'unroute',
  'goto',
  'url',
  'reload',
  'goBack',
  'goForward',
  'evaluate',
  ...PLAYWRIGHT_ACTION_METHODS,
  'isChecked',
  'isDisabled',
  'isEditable',
  'inputValue',
  'getAttribute',
  'waitForSelector',
  'title',
  'waitForLoadState',
  'waitForFunction',
  'waitForResponse',
  'waitForTimeout',
  'screenshot',
  'video',
  'context',
  ...PLAYWRIGHT_LOCATOR_RETURNING_METHODS,
  'innerHTML',
  'isElementVisible',
  'count',
]);

export const PLAYWRIGHT_LOCATOR_METHODS: ReadonlySet<string> = new Set([
  'allAttributes',
  'boundingBox',
  ...PLAYWRIGHT_ACTION_METHODS,
  'textContent',
  'inputValue',
  'isVisible',
  'isChecked',
  'isDisabled',
  'isEditable',
  'getAttribute',
  'innerHTML',
  'count',
  ...PLAYWRIGHT_LOCATOR_RETURNING_METHODS,
  'evaluate',
  'all',
  'allTextContents',
  'elementHandles',
]);
