/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestSentryRouteImport } from './routes/test-sentry'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.xml]'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as AdminTutorialsRouteImport } from './routes/admin/tutorials'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminDebugRouteImport } from './routes/admin/debug'
import { Route as AdminChallengesRouteImport } from './routes/admin/challenges'
import { Route as AdminBugsRouteImport } from './routes/admin/bugs'
import { Route as AdminAchievementsRouteImport } from './routes/admin/achievements'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleResetPasswordRouteImport } from './routes/$locale/reset-password'
import { Route as LocaleRegisterRouteImport } from './routes/$locale/register'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleLeaderboardRouteImport } from './routes/$locale/leaderboard'
import { Route as LocaleForgotPasswordRouteImport } from './routes/$locale/forgot-password'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleConfirmSubscriptionRouteImport } from './routes/$locale/confirm-subscription'
import { Route as LocaleChangelogRouteImport } from './routes/$locale/changelog'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleAuthenticatedRouteImport } from './routes/$locale/_authenticated'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users.index'
import { Route as LocaleTutorialsIndexRouteImport } from './routes/$locale/tutorials/index'
import { Route as LocaleChallengesIndexRouteImport } from './routes/$locale/challenges/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as LocaleTutorialsSlugRouteImport } from './routes/$locale/tutorials/$slug'
import { Route as LocaleChallengesSlugRouteImport } from './routes/$locale/challenges/$slug'
import { Route as LocaleAuthenticatedProfileRouteImport } from './routes/$locale/_authenticated/profile'

const TestSentryRoute = TestSentryRouteImport.update({
  id: '/test-sentry',
  path: '/test-sentry',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTutorialsRoute = AdminTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDebugRoute = AdminDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChallengesRoute = AdminChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBugsRoute = AdminBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AdminRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleResetPasswordRoute = LocaleResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRegisterRoute = LocaleRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLeaderboardRoute = LocaleLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleForgotPasswordRoute = LocaleForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleConfirmSubscriptionRoute =
  LocaleConfirmSubscriptionRouteImport.update({
    id: '/confirm-subscription',
    path: '/confirm-subscription',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleChangelogRoute = LocaleChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthenticatedRoute = LocaleAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const LocaleTutorialsIndexRoute = LocaleTutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChallengesIndexRoute = LocaleChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const LocaleTutorialsSlugRoute = LocaleTutorialsSlugRouteImport.update({
  id: '/tutorials/$slug',
  path: '/tutorials/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChallengesSlugRoute = LocaleChallengesSlugRouteImport.update({
  id: '/challenges/$slug',
  path: '/challenges/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthenticatedProfileRoute =
  LocaleAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LocaleAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$locale': typeof LocaleAuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-sentry': typeof TestSentryRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/confirm-subscription': typeof LocaleConfirmSubscriptionRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/leaderboard': typeof LocaleLeaderboardRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/debug': typeof AdminDebugRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/api/og': typeof ApiOgRoute
  '/docs/api': typeof DocsApiRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/$locale/profile': typeof LocaleAuthenticatedProfileRoute
  '/$locale/challenges/$slug': typeof LocaleChallengesSlugRoute
  '/$locale/tutorials/$slug': typeof LocaleTutorialsSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/challenges': typeof LocaleChallengesIndexRoute
  '/$locale/tutorials': typeof LocaleTutorialsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-sentry': typeof TestSentryRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/confirm-subscription': typeof LocaleConfirmSubscriptionRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/leaderboard': typeof LocaleLeaderboardRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/debug': typeof AdminDebugRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/api/og': typeof ApiOgRoute
  '/docs/api': typeof DocsApiRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/$locale/profile': typeof LocaleAuthenticatedProfileRoute
  '/$locale/challenges/$slug': typeof LocaleChallengesSlugRoute
  '/$locale/tutorials/$slug': typeof LocaleTutorialsSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/challenges': typeof LocaleChallengesIndexRoute
  '/$locale/tutorials': typeof LocaleTutorialsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-sentry': typeof TestSentryRoute
  '/$locale/_authenticated': typeof LocaleAuthenticatedRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/confirm-subscription': typeof LocaleConfirmSubscriptionRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/leaderboard': typeof LocaleLeaderboardRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/debug': typeof AdminDebugRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/api/og': typeof ApiOgRoute
  '/docs/api': typeof DocsApiRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/$locale/_authenticated/profile': typeof LocaleAuthenticatedProfileRoute
  '/$locale/challenges/$slug': typeof LocaleChallengesSlugRoute
  '/$locale/tutorials/$slug': typeof LocaleTutorialsSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/challenges/': typeof LocaleChallengesIndexRoute
  '/$locale/tutorials/': typeof LocaleTutorialsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$locale'
    | '/admin'
    | '/sitemap.xml'
    | '/test-sentry'
    | '/$locale/about'
    | '/$locale/changelog'
    | '/$locale/confirm-subscription'
    | '/$locale/contact'
    | '/$locale/forgot-password'
    | '/$locale/leaderboard'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/register'
    | '/$locale/reset-password'
    | '/$locale/terms'
    | '/admin/achievements'
    | '/admin/bugs'
    | '/admin/challenges'
    | '/admin/debug'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/tutorials'
    | '/api/og'
    | '/docs/api'
    | '/robots/txt'
    | '/$locale/'
    | '/admin/'
    | '/docs'
    | '/$locale/profile'
    | '/$locale/challenges/$slug'
    | '/$locale/tutorials/$slug'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/$locale/challenges'
    | '/$locale/tutorials'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/sitemap.xml'
    | '/test-sentry'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/changelog'
    | '/$locale/confirm-subscription'
    | '/$locale/contact'
    | '/$locale/forgot-password'
    | '/$locale/leaderboard'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/register'
    | '/$locale/reset-password'
    | '/$locale/terms'
    | '/admin/achievements'
    | '/admin/bugs'
    | '/admin/challenges'
    | '/admin/debug'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/tutorials'
    | '/api/og'
    | '/docs/api'
    | '/robots/txt'
    | '/admin'
    | '/docs'
    | '/$locale/profile'
    | '/$locale/challenges/$slug'
    | '/$locale/tutorials/$slug'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/$locale/challenges'
    | '/$locale/tutorials'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$locale'
    | '/admin'
    | '/sitemap.xml'
    | '/test-sentry'
    | '/$locale/_authenticated'
    | '/$locale/about'
    | '/$locale/changelog'
    | '/$locale/confirm-subscription'
    | '/$locale/contact'
    | '/$locale/forgot-password'
    | '/$locale/leaderboard'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/register'
    | '/$locale/reset-password'
    | '/$locale/terms'
    | '/admin/achievements'
    | '/admin/bugs'
    | '/admin/challenges'
    | '/admin/debug'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/tutorials'
    | '/api/og'
    | '/docs/api'
    | '/robots/txt'
    | '/$locale/'
    | '/admin/'
    | '/docs/'
    | '/$locale/_authenticated/profile'
    | '/$locale/challenges/$slug'
    | '/$locale/tutorials/$slug'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/$locale/challenges/'
    | '/$locale/tutorials/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestSentryRoute: typeof TestSentryRoute
  ApiOgRoute: typeof ApiOgRoute
  DocsApiRoute: typeof DocsApiRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-sentry': {
      id: '/test-sentry'
      path: '/test-sentry'
      fullPath: '/test-sentry'
      preLoaderRoute: typeof TestSentryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutorials': {
      id: '/admin/tutorials'
      path: '/tutorials'
      fullPath: '/admin/tutorials'
      preLoaderRoute: typeof AdminTutorialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/debug': {
      id: '/admin/debug'
      path: '/debug'
      fullPath: '/admin/debug'
      preLoaderRoute: typeof AdminDebugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/challenges': {
      id: '/admin/challenges'
      path: '/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AdminChallengesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bugs': {
      id: '/admin/bugs'
      path: '/bugs'
      fullPath: '/admin/bugs'
      preLoaderRoute: typeof AdminBugsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reset-password': {
      id: '/$locale/reset-password'
      path: '/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleResetPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/register': {
      id: '/$locale/register'
      path: '/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleRegisterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/leaderboard': {
      id: '/$locale/leaderboard'
      path: '/leaderboard'
      fullPath: '/$locale/leaderboard'
      preLoaderRoute: typeof LocaleLeaderboardRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/forgot-password': {
      id: '/$locale/forgot-password'
      path: '/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleForgotPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/confirm-subscription': {
      id: '/$locale/confirm-subscription'
      path: '/confirm-subscription'
      fullPath: '/$locale/confirm-subscription'
      preLoaderRoute: typeof LocaleConfirmSubscriptionRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/changelog': {
      id: '/$locale/changelog'
      path: '/changelog'
      fullPath: '/$locale/changelog'
      preLoaderRoute: typeof LocaleChangelogRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authenticated': {
      id: '/$locale/_authenticated'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthenticatedRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$locale/tutorials/': {
      id: '/$locale/tutorials/'
      path: '/tutorials'
      fullPath: '/$locale/tutorials'
      preLoaderRoute: typeof LocaleTutorialsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/challenges/': {
      id: '/$locale/challenges/'
      path: '/challenges'
      fullPath: '/$locale/challenges'
      preLoaderRoute: typeof LocaleChallengesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$locale/tutorials/$slug': {
      id: '/$locale/tutorials/$slug'
      path: '/tutorials/$slug'
      fullPath: '/$locale/tutorials/$slug'
      preLoaderRoute: typeof LocaleTutorialsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/challenges/$slug': {
      id: '/$locale/challenges/$slug'
      path: '/challenges/$slug'
      fullPath: '/$locale/challenges/$slug'
      preLoaderRoute: typeof LocaleChallengesSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authenticated/profile': {
      id: '/$locale/_authenticated/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleAuthenticatedProfileRouteImport
      parentRoute: typeof LocaleAuthenticatedRoute
    }
  }
}

interface LocaleAuthenticatedRouteChildren {
  LocaleAuthenticatedProfileRoute: typeof LocaleAuthenticatedProfileRoute
}

const LocaleAuthenticatedRouteChildren: LocaleAuthenticatedRouteChildren = {
  LocaleAuthenticatedProfileRoute: LocaleAuthenticatedProfileRoute,
}

const LocaleAuthenticatedRouteWithChildren =
  LocaleAuthenticatedRoute._addFileChildren(LocaleAuthenticatedRouteChildren)

interface LocaleRouteChildren {
  LocaleAuthenticatedRoute: typeof LocaleAuthenticatedRouteWithChildren
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleChangelogRoute: typeof LocaleChangelogRoute
  LocaleConfirmSubscriptionRoute: typeof LocaleConfirmSubscriptionRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleForgotPasswordRoute: typeof LocaleForgotPasswordRoute
  LocaleLeaderboardRoute: typeof LocaleLeaderboardRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleRegisterRoute: typeof LocaleRegisterRoute
  LocaleResetPasswordRoute: typeof LocaleResetPasswordRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleChallengesSlugRoute: typeof LocaleChallengesSlugRoute
  LocaleTutorialsSlugRoute: typeof LocaleTutorialsSlugRoute
  LocaleChallengesIndexRoute: typeof LocaleChallengesIndexRoute
  LocaleTutorialsIndexRoute: typeof LocaleTutorialsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAuthenticatedRoute: LocaleAuthenticatedRouteWithChildren,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleChangelogRoute: LocaleChangelogRoute,
  LocaleConfirmSubscriptionRoute: LocaleConfirmSubscriptionRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleForgotPasswordRoute: LocaleForgotPasswordRoute,
  LocaleLeaderboardRoute: LocaleLeaderboardRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleRegisterRoute: LocaleRegisterRoute,
  LocaleResetPasswordRoute: LocaleResetPasswordRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleChallengesSlugRoute: LocaleChallengesSlugRoute,
  LocaleTutorialsSlugRoute: LocaleTutorialsSlugRoute,
  LocaleChallengesIndexRoute: LocaleChallengesIndexRoute,
  LocaleTutorialsIndexRoute: LocaleTutorialsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface AdminRouteChildren {
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminBugsRoute: typeof AdminBugsRoute
  AdminChallengesRoute: typeof AdminChallengesRoute
  AdminDebugRoute: typeof AdminDebugRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTutorialsRoute: typeof AdminTutorialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminBugsRoute: AdminBugsRoute,
  AdminChallengesRoute: AdminChallengesRoute,
  AdminDebugRoute: AdminDebugRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTutorialsRoute: AdminTutorialsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestSentryRoute: TestSentryRoute,
  ApiOgRoute: ApiOgRoute,
  DocsApiRoute: DocsApiRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
