/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialsIndexRouteImport } from './routes/tutorials/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as TutorialsSlugRouteImport } from './routes/tutorials/$slug'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as ChallengesSlugRouteImport } from './routes/challenges/$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiTutorialsIndexRouteImport } from './routes/api/tutorials/index'
import { Route as ApiSubmissionsIndexRouteImport } from './routes/api/submissions/index'
import { Route as ApiLeaderboardIndexRouteImport } from './routes/api/leaderboard/index'
import { Route as ApiChallengesIndexRouteImport } from './routes/api/challenges/index'
import { Route as ApiBugReportsIndexRouteImport } from './routes/api/bug-reports/index'
import { Route as ApiUsersMeRouteImport } from './routes/api/users/me'
import { Route as ApiTutorialsSlugRouteImport } from './routes/api/tutorials/$slug'
import { Route as ApiChallengesSlugRouteImport } from './routes/api/challenges/$slug'
import { Route as ApiAuthResendVerificationRouteImport } from './routes/api/auth/resend-verification'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTutorialsSlugProgressRouteImport } from './routes/api/tutorials/$slug/progress'
import { Route as ApiTutorialsSlugCompleteRouteImport } from './routes/api/tutorials/$slug/complete'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsIndexRoute = TutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsSlugRoute = TutorialsSlugRouteImport.update({
  id: '/tutorials/$slug',
  path: '/tutorials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesSlugRoute = ChallengesSlugRouteImport.update({
  id: '/challenges/$slug',
  path: '/challenges/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTutorialsIndexRoute = ApiTutorialsIndexRouteImport.update({
  id: '/api/tutorials/',
  path: '/api/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsIndexRoute = ApiSubmissionsIndexRouteImport.update({
  id: '/api/submissions/',
  path: '/api/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardIndexRoute = ApiLeaderboardIndexRouteImport.update({
  id: '/api/leaderboard/',
  path: '/api/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesIndexRoute = ApiChallengesIndexRouteImport.update({
  id: '/api/challenges/',
  path: '/api/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBugReportsIndexRoute = ApiBugReportsIndexRouteImport.update({
  id: '/api/bug-reports/',
  path: '/api/bug-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersMeRoute = ApiUsersMeRouteImport.update({
  id: '/api/users/me',
  path: '/api/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorialsSlugRoute = ApiTutorialsSlugRouteImport.update({
  id: '/api/tutorials/$slug',
  path: '/api/tutorials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesSlugRoute = ApiChallengesSlugRouteImport.update({
  id: '/api/challenges/$slug',
  path: '/api/challenges/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResendVerificationRoute =
  ApiAuthResendVerificationRouteImport.update({
    id: '/api/auth/resend-verification',
    path: '/api/auth/resend-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorialsSlugProgressRoute =
  ApiTutorialsSlugProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => ApiTutorialsSlugRoute,
  } as any)
const ApiTutorialsSlugCompleteRoute =
  ApiTutorialsSlugCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiTutorialsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/docs/api': typeof DocsApiRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/challenges': typeof ChallengesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/tutorials': typeof TutorialsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/resend-verification': typeof ApiAuthResendVerificationRoute
  '/api/challenges/$slug': typeof ApiChallengesSlugRoute
  '/api/tutorials/$slug': typeof ApiTutorialsSlugRouteWithChildren
  '/api/users/me': typeof ApiUsersMeRoute
  '/api/bug-reports': typeof ApiBugReportsIndexRoute
  '/api/challenges': typeof ApiChallengesIndexRoute
  '/api/leaderboard': typeof ApiLeaderboardIndexRoute
  '/api/submissions': typeof ApiSubmissionsIndexRoute
  '/api/tutorials': typeof ApiTutorialsIndexRoute
  '/api/tutorials/$slug/complete': typeof ApiTutorialsSlugCompleteRoute
  '/api/tutorials/$slug/progress': typeof ApiTutorialsSlugProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/docs/api': typeof DocsApiRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/challenges': typeof ChallengesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/tutorials': typeof TutorialsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/resend-verification': typeof ApiAuthResendVerificationRoute
  '/api/challenges/$slug': typeof ApiChallengesSlugRoute
  '/api/tutorials/$slug': typeof ApiTutorialsSlugRouteWithChildren
  '/api/users/me': typeof ApiUsersMeRoute
  '/api/bug-reports': typeof ApiBugReportsIndexRoute
  '/api/challenges': typeof ApiChallengesIndexRoute
  '/api/leaderboard': typeof ApiLeaderboardIndexRoute
  '/api/submissions': typeof ApiSubmissionsIndexRoute
  '/api/tutorials': typeof ApiTutorialsIndexRoute
  '/api/tutorials/$slug/complete': typeof ApiTutorialsSlugCompleteRoute
  '/api/tutorials/$slug/progress': typeof ApiTutorialsSlugProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/docs/api': typeof DocsApiRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/tutorials/': typeof TutorialsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/resend-verification': typeof ApiAuthResendVerificationRoute
  '/api/challenges/$slug': typeof ApiChallengesSlugRoute
  '/api/tutorials/$slug': typeof ApiTutorialsSlugRouteWithChildren
  '/api/users/me': typeof ApiUsersMeRoute
  '/api/bug-reports/': typeof ApiBugReportsIndexRoute
  '/api/challenges/': typeof ApiChallengesIndexRoute
  '/api/leaderboard/': typeof ApiLeaderboardIndexRoute
  '/api/submissions/': typeof ApiSubmissionsIndexRoute
  '/api/tutorials/': typeof ApiTutorialsIndexRoute
  '/api/tutorials/$slug/complete': typeof ApiTutorialsSlugCompleteRoute
  '/api/tutorials/$slug/progress': typeof ApiTutorialsSlugProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/reset-password'
    | '/profile'
    | '/settings'
    | '/challenges/$slug'
    | '/docs/api'
    | '/tutorials/$slug'
    | '/challenges'
    | '/docs'
    | '/tutorials'
    | '/api/auth/$'
    | '/api/auth/resend-verification'
    | '/api/challenges/$slug'
    | '/api/tutorials/$slug'
    | '/api/users/me'
    | '/api/bug-reports'
    | '/api/challenges'
    | '/api/leaderboard'
    | '/api/submissions'
    | '/api/tutorials'
    | '/api/tutorials/$slug/complete'
    | '/api/tutorials/$slug/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/reset-password'
    | '/profile'
    | '/settings'
    | '/challenges/$slug'
    | '/docs/api'
    | '/tutorials/$slug'
    | '/challenges'
    | '/docs'
    | '/tutorials'
    | '/api/auth/$'
    | '/api/auth/resend-verification'
    | '/api/challenges/$slug'
    | '/api/tutorials/$slug'
    | '/api/users/me'
    | '/api/bug-reports'
    | '/api/challenges'
    | '/api/leaderboard'
    | '/api/submissions'
    | '/api/tutorials'
    | '/api/tutorials/$slug/complete'
    | '/api/tutorials/$slug/progress'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/reset-password'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/challenges/$slug'
    | '/docs/api'
    | '/tutorials/$slug'
    | '/challenges/'
    | '/docs/'
    | '/tutorials/'
    | '/api/auth/$'
    | '/api/auth/resend-verification'
    | '/api/challenges/$slug'
    | '/api/tutorials/$slug'
    | '/api/users/me'
    | '/api/bug-reports/'
    | '/api/challenges/'
    | '/api/leaderboard/'
    | '/api/submissions/'
    | '/api/tutorials/'
    | '/api/tutorials/$slug/complete'
    | '/api/tutorials/$slug/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ChallengesSlugRoute: typeof ChallengesSlugRoute
  DocsApiRoute: typeof DocsApiRoute
  TutorialsSlugRoute: typeof TutorialsSlugRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  TutorialsIndexRoute: typeof TutorialsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthResendVerificationRoute: typeof ApiAuthResendVerificationRoute
  ApiChallengesSlugRoute: typeof ApiChallengesSlugRoute
  ApiTutorialsSlugRoute: typeof ApiTutorialsSlugRouteWithChildren
  ApiUsersMeRoute: typeof ApiUsersMeRoute
  ApiBugReportsIndexRoute: typeof ApiBugReportsIndexRoute
  ApiChallengesIndexRoute: typeof ApiChallengesIndexRoute
  ApiLeaderboardIndexRoute: typeof ApiLeaderboardIndexRoute
  ApiSubmissionsIndexRoute: typeof ApiSubmissionsIndexRoute
  ApiTutorialsIndexRoute: typeof ApiTutorialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/': {
      id: '/tutorials/'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/$slug': {
      id: '/tutorials/$slug'
      path: '/tutorials/$slug'
      fullPath: '/tutorials/$slug'
      preLoaderRoute: typeof TutorialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$slug': {
      id: '/challenges/$slug'
      path: '/challenges/$slug'
      fullPath: '/challenges/$slug'
      preLoaderRoute: typeof ChallengesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/tutorials/': {
      id: '/api/tutorials/'
      path: '/api/tutorials'
      fullPath: '/api/tutorials'
      preLoaderRoute: typeof ApiTutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions/': {
      id: '/api/submissions/'
      path: '/api/submissions'
      fullPath: '/api/submissions'
      preLoaderRoute: typeof ApiSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard/': {
      id: '/api/leaderboard/'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges/': {
      id: '/api/challenges/'
      path: '/api/challenges'
      fullPath: '/api/challenges'
      preLoaderRoute: typeof ApiChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bug-reports/': {
      id: '/api/bug-reports/'
      path: '/api/bug-reports'
      fullPath: '/api/bug-reports'
      preLoaderRoute: typeof ApiBugReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/me': {
      id: '/api/users/me'
      path: '/api/users/me'
      fullPath: '/api/users/me'
      preLoaderRoute: typeof ApiUsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutorials/$slug': {
      id: '/api/tutorials/$slug'
      path: '/api/tutorials/$slug'
      fullPath: '/api/tutorials/$slug'
      preLoaderRoute: typeof ApiTutorialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges/$slug': {
      id: '/api/challenges/$slug'
      path: '/api/challenges/$slug'
      fullPath: '/api/challenges/$slug'
      preLoaderRoute: typeof ApiChallengesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/resend-verification': {
      id: '/api/auth/resend-verification'
      path: '/api/auth/resend-verification'
      fullPath: '/api/auth/resend-verification'
      preLoaderRoute: typeof ApiAuthResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutorials/$slug/progress': {
      id: '/api/tutorials/$slug/progress'
      path: '/progress'
      fullPath: '/api/tutorials/$slug/progress'
      preLoaderRoute: typeof ApiTutorialsSlugProgressRouteImport
      parentRoute: typeof ApiTutorialsSlugRoute
    }
    '/api/tutorials/$slug/complete': {
      id: '/api/tutorials/$slug/complete'
      path: '/complete'
      fullPath: '/api/tutorials/$slug/complete'
      preLoaderRoute: typeof ApiTutorialsSlugCompleteRouteImport
      parentRoute: typeof ApiTutorialsSlugRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiTutorialsSlugRouteChildren {
  ApiTutorialsSlugCompleteRoute: typeof ApiTutorialsSlugCompleteRoute
  ApiTutorialsSlugProgressRoute: typeof ApiTutorialsSlugProgressRoute
}

const ApiTutorialsSlugRouteChildren: ApiTutorialsSlugRouteChildren = {
  ApiTutorialsSlugCompleteRoute: ApiTutorialsSlugCompleteRoute,
  ApiTutorialsSlugProgressRoute: ApiTutorialsSlugProgressRoute,
}

const ApiTutorialsSlugRouteWithChildren =
  ApiTutorialsSlugRoute._addFileChildren(ApiTutorialsSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ChallengesSlugRoute: ChallengesSlugRoute,
  DocsApiRoute: DocsApiRoute,
  TutorialsSlugRoute: TutorialsSlugRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  TutorialsIndexRoute: TutorialsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthResendVerificationRoute: ApiAuthResendVerificationRoute,
  ApiChallengesSlugRoute: ApiChallengesSlugRoute,
  ApiTutorialsSlugRoute: ApiTutorialsSlugRouteWithChildren,
  ApiUsersMeRoute: ApiUsersMeRoute,
  ApiBugReportsIndexRoute: ApiBugReportsIndexRoute,
  ApiChallengesIndexRoute: ApiChallengesIndexRoute,
  ApiLeaderboardIndexRoute: ApiLeaderboardIndexRoute,
  ApiSubmissionsIndexRoute: ApiSubmissionsIndexRoute,
  ApiTutorialsIndexRoute: ApiTutorialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
