/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminChallengesRouteImport } from './routes/admin/challenges'
import { Route as AdminBugsRouteImport } from './routes/admin/bugs'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleResetPasswordRouteImport } from './routes/$locale/reset-password'
import { Route as LocaleRegisterRouteImport } from './routes/$locale/register'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleLeaderboardRouteImport } from './routes/$locale/leaderboard'
import { Route as LocaleForgotPasswordRouteImport } from './routes/$locale/forgot-password'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleAuthenticatedRouteImport } from './routes/$locale/_authenticated'
import { Route as LocaleTutorialsIndexRouteImport } from './routes/$locale/tutorials/index'
import { Route as LocaleChallengesIndexRouteImport } from './routes/$locale/challenges/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LocaleTutorialsSlugRouteImport } from './routes/$locale/tutorials/$slug'
import { Route as LocaleChallengesSlugRouteImport } from './routes/$locale/challenges/$slug'
import { Route as LocaleAuthenticatedSettingsRouteImport } from './routes/$locale/_authenticated/settings'
import { Route as LocaleAuthenticatedProfileRouteImport } from './routes/$locale/_authenticated/profile'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChallengesRoute = AdminChallengesRouteImport.update({
  id: '/admin/challenges',
  path: '/admin/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBugsRoute = AdminBugsRouteImport.update({
  id: '/admin/bugs',
  path: '/admin/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleResetPasswordRoute = LocaleResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRegisterRoute = LocaleRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLeaderboardRoute = LocaleLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleForgotPasswordRoute = LocaleForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthenticatedRoute = LocaleAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTutorialsIndexRoute = LocaleTutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChallengesIndexRoute = LocaleChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTutorialsSlugRoute = LocaleTutorialsSlugRouteImport.update({
  id: '/tutorials/$slug',
  path: '/tutorials/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChallengesSlugRoute = LocaleChallengesSlugRouteImport.update({
  id: '/challenges/$slug',
  path: '/challenges/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthenticatedSettingsRoute =
  LocaleAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LocaleAuthenticatedRoute,
  } as any)
const LocaleAuthenticatedProfileRoute =
  LocaleAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LocaleAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$locale': typeof LocaleAuthenticatedRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/leaderboard': typeof LocaleLeaderboardRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/users': typeof AdminUsersRoute
  '/docs/api': typeof DocsApiRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/$locale/profile': typeof LocaleAuthenticatedProfileRoute
  '/$locale/settings': typeof LocaleAuthenticatedSettingsRoute
  '/$locale/challenges/$slug': typeof LocaleChallengesSlugRoute
  '/$locale/tutorials/$slug': typeof LocaleTutorialsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/challenges': typeof LocaleChallengesIndexRoute
  '/$locale/tutorials': typeof LocaleTutorialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/leaderboard': typeof LocaleLeaderboardRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/users': typeof AdminUsersRoute
  '/docs/api': typeof DocsApiRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/$locale/profile': typeof LocaleAuthenticatedProfileRoute
  '/$locale/settings': typeof LocaleAuthenticatedSettingsRoute
  '/$locale/challenges/$slug': typeof LocaleChallengesSlugRoute
  '/$locale/tutorials/$slug': typeof LocaleTutorialsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/challenges': typeof LocaleChallengesIndexRoute
  '/$locale/tutorials': typeof LocaleTutorialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_authenticated': typeof LocaleAuthenticatedRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/leaderboard': typeof LocaleLeaderboardRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/users': typeof AdminUsersRoute
  '/docs/api': typeof DocsApiRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/$locale/_authenticated/profile': typeof LocaleAuthenticatedProfileRoute
  '/$locale/_authenticated/settings': typeof LocaleAuthenticatedSettingsRoute
  '/$locale/challenges/$slug': typeof LocaleChallengesSlugRoute
  '/$locale/tutorials/$slug': typeof LocaleTutorialsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/challenges/': typeof LocaleChallengesIndexRoute
  '/$locale/tutorials/': typeof LocaleTutorialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/forgot-password'
    | '/$locale/leaderboard'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/register'
    | '/$locale/reset-password'
    | '/$locale/terms'
    | '/admin/bugs'
    | '/admin/challenges'
    | '/admin/users'
    | '/docs/api'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/$locale/'
    | '/admin'
    | '/docs'
    | '/$locale/profile'
    | '/$locale/settings'
    | '/$locale/challenges/$slug'
    | '/$locale/tutorials/$slug'
    | '/api/auth/$'
    | '/$locale/challenges'
    | '/$locale/tutorials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/forgot-password'
    | '/$locale/leaderboard'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/register'
    | '/$locale/reset-password'
    | '/$locale/terms'
    | '/admin/bugs'
    | '/admin/challenges'
    | '/admin/users'
    | '/docs/api'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/admin'
    | '/docs'
    | '/$locale/profile'
    | '/$locale/settings'
    | '/$locale/challenges/$slug'
    | '/$locale/tutorials/$slug'
    | '/api/auth/$'
    | '/$locale/challenges'
    | '/$locale/tutorials'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$locale'
    | '/$locale/_authenticated'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/forgot-password'
    | '/$locale/leaderboard'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/register'
    | '/$locale/reset-password'
    | '/$locale/terms'
    | '/admin/bugs'
    | '/admin/challenges'
    | '/admin/users'
    | '/docs/api'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/$locale/'
    | '/admin/'
    | '/docs/'
    | '/$locale/_authenticated/profile'
    | '/$locale/_authenticated/settings'
    | '/$locale/challenges/$slug'
    | '/$locale/tutorials/$slug'
    | '/api/auth/$'
    | '/$locale/challenges/'
    | '/$locale/tutorials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminBugsRoute: typeof AdminBugsRoute
  AdminChallengesRoute: typeof AdminChallengesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DocsApiRoute: typeof DocsApiRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/challenges': {
      id: '/admin/challenges'
      path: '/admin/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AdminChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bugs': {
      id: '/admin/bugs'
      path: '/admin/bugs'
      fullPath: '/admin/bugs'
      preLoaderRoute: typeof AdminBugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reset-password': {
      id: '/$locale/reset-password'
      path: '/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleResetPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/register': {
      id: '/$locale/register'
      path: '/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleRegisterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/leaderboard': {
      id: '/$locale/leaderboard'
      path: '/leaderboard'
      fullPath: '/$locale/leaderboard'
      preLoaderRoute: typeof LocaleLeaderboardRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/forgot-password': {
      id: '/$locale/forgot-password'
      path: '/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleForgotPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authenticated': {
      id: '/$locale/_authenticated'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthenticatedRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tutorials/': {
      id: '/$locale/tutorials/'
      path: '/tutorials'
      fullPath: '/$locale/tutorials'
      preLoaderRoute: typeof LocaleTutorialsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/challenges/': {
      id: '/$locale/challenges/'
      path: '/challenges'
      fullPath: '/$locale/challenges'
      preLoaderRoute: typeof LocaleChallengesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/tutorials/$slug': {
      id: '/$locale/tutorials/$slug'
      path: '/tutorials/$slug'
      fullPath: '/$locale/tutorials/$slug'
      preLoaderRoute: typeof LocaleTutorialsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/challenges/$slug': {
      id: '/$locale/challenges/$slug'
      path: '/challenges/$slug'
      fullPath: '/$locale/challenges/$slug'
      preLoaderRoute: typeof LocaleChallengesSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authenticated/settings': {
      id: '/$locale/_authenticated/settings'
      path: '/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleAuthenticatedSettingsRouteImport
      parentRoute: typeof LocaleAuthenticatedRoute
    }
    '/$locale/_authenticated/profile': {
      id: '/$locale/_authenticated/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleAuthenticatedProfileRouteImport
      parentRoute: typeof LocaleAuthenticatedRoute
    }
  }
}

interface LocaleAuthenticatedRouteChildren {
  LocaleAuthenticatedProfileRoute: typeof LocaleAuthenticatedProfileRoute
  LocaleAuthenticatedSettingsRoute: typeof LocaleAuthenticatedSettingsRoute
}

const LocaleAuthenticatedRouteChildren: LocaleAuthenticatedRouteChildren = {
  LocaleAuthenticatedProfileRoute: LocaleAuthenticatedProfileRoute,
  LocaleAuthenticatedSettingsRoute: LocaleAuthenticatedSettingsRoute,
}

const LocaleAuthenticatedRouteWithChildren =
  LocaleAuthenticatedRoute._addFileChildren(LocaleAuthenticatedRouteChildren)

interface LocaleRouteChildren {
  LocaleAuthenticatedRoute: typeof LocaleAuthenticatedRouteWithChildren
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleForgotPasswordRoute: typeof LocaleForgotPasswordRoute
  LocaleLeaderboardRoute: typeof LocaleLeaderboardRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleRegisterRoute: typeof LocaleRegisterRoute
  LocaleResetPasswordRoute: typeof LocaleResetPasswordRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleChallengesSlugRoute: typeof LocaleChallengesSlugRoute
  LocaleTutorialsSlugRoute: typeof LocaleTutorialsSlugRoute
  LocaleChallengesIndexRoute: typeof LocaleChallengesIndexRoute
  LocaleTutorialsIndexRoute: typeof LocaleTutorialsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAuthenticatedRoute: LocaleAuthenticatedRouteWithChildren,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleForgotPasswordRoute: LocaleForgotPasswordRoute,
  LocaleLeaderboardRoute: LocaleLeaderboardRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleRegisterRoute: LocaleRegisterRoute,
  LocaleResetPasswordRoute: LocaleResetPasswordRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleChallengesSlugRoute: LocaleChallengesSlugRoute,
  LocaleTutorialsSlugRoute: LocaleTutorialsSlugRoute,
  LocaleChallengesIndexRoute: LocaleChallengesIndexRoute,
  LocaleTutorialsIndexRoute: LocaleTutorialsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AdminBugsRoute: AdminBugsRoute,
  AdminChallengesRoute: AdminChallengesRoute,
  AdminUsersRoute: AdminUsersRoute,
  DocsApiRoute: DocsApiRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  AdminIndexRoute: AdminIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
